version: '3.8'
services:
  discovery-service:
    image: carcompany/discovery-service
    container_name: discovery-service
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://discovery-service:8761" ]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "8761:8761"
    networks:
      - lease-a-car-network
  gateway-service:
    image: carcompany/gateway-service
    container_name: gateway-service
    depends_on:
      discovery-service:
        condition: service_healthy
      car-service:
        condition: service_healthy
      customer-service:
        condition: service_started
      lease-service:
        condition: service_started
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - lease-a-car-network

  customer-service:
    image: carcompany/customer-service
    container_name: customer-service
    build:
      context: ./customer-service
      dockerfile: Dockerfile
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://customer-service:8081" ]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      discovery-service:
        condition: service_started
    networks:
      - lease-a-car-network

  car-service:
    image: carcompany/car-service
    container_name: car-service
    build:
      context: ./car-service
      dockerfile: Dockerfile
    depends_on:
      discovery-service:
        condition: service_started
    networks:
      - lease-a-car-network

  lease-service:
    image: carcompany/lease-service
    container_name: lease-service
    build:
      context: ./lease-service
      dockerfile: Dockerfile
    depends_on:
      discovery-service:
        condition: service_started
    networks:
      - lease-a-car-network

networks:
  lease-a-car-network:
    driver: bridge