lease:
  gateway-service:
    url: http://gateway-service:8080
spring:
  application:
    name: lease-service
  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: db.changelog-lease.xml
  h2:
    console:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

server:
  port: 8083