gateway:
  customer-service:
    name: customer-service
    context: /customers
  car-service:
    name: car-service
    context: /cars
  lease-service:
    name: lease-service
    context: /leases
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka
server:
  port: 8080
